type=command
date=${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day}
retries=999
dependencies=dim_Einstein_data_plan,dim_Einstein_location,dim_Einstein_currency,dim_Einstein_promotions,dim_Einstein_data_plan_rel_group,dim_Einstein_data_plan_group,dim_Einstein_data_plan_provider,dim_Einstein_provider
command=sh /home/ops/warehouse-redtea/dwd/Einstein/dwd_Einstein_data_plan_detail.sh ${date}
