type=command
date=${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day}
retries=999
dependencies=dim_Bumblebee_bundle,dim_Bumblebee_carrier,dim_Bumblebee_channel,dim_Bumblebee_bundle_group_bundle,dim_Bumblebee_bundle_group,dim_Bumblebee_bundle_price,dim_Bumblebee_local_carrier_price_history
command=sh /home/ops/warehouse-redtea/dwd/Bumblebee/dwd_Bumblebee_bundle_detail.sh ${date}
