type=command
retries=999
date=${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day}
dependencies=ods_Einstein_device,ods_Einstein_register_device,dwd_Einstein_orders_detail,dwd_Einstein_order_imsi_profile_relation,dwd_Bumblebee_imsi_transaction_cdr_raw,dwd_Bumblebee_imsi_transaction_detail,ods_Einstein_unified_identification
command=sh /home/ops/warehouse-redtea/dwd/Einstein/dwd_Einstein_device_detail.sh ${date}
