type=command
retries=999
date=${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day}
retries=999
dependencies=dwd_Nobel_users_detail,dwd_Nobel_orders_detail,dwd_Bumblebee_imsi_transaction_detail,dwd_Bumblebee_imsi_transaction_cdr_raw,dwd_Einstein_device_detail,dwd_Einstein_orders_detail,dwd_Einstein_order_imsi_profile_relation,dwd_Bethune_user_detail,dwd_Bethune_order_detail,dwd_Bumblebee_bundle_detail
command=sh /home/ops/warehouse-redtea/dws/dws_redtea_user.sh ${date}
